"""add_gl_username_to_user

Revision ID: cc260f59670a
Revises: c1d2e3f4g5h6
Create Date: 2026-04-26 06:12:50.018467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc260f59670a'
down_revision: Union[str, None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gl_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_gl_username'), 'users', ['gl_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gl_username'), table_name='users')
    op.drop_column('users', 'gl_username')
    # ### end Alembic commands ###
